회원가입화면 #step1 lasagna, jake
yagom-academy/ios-signup-flow pull request #1
Opened 2020-11-30 12:23 UTC by jryoun1

구현사항
1. UserInformation 타입 구현

2020-11-30 12:30 UTC, yagom requested changes
빠르게 PR 보냈네요!
코멘트 남겨둡니다 :)

2020-11-30 12:30 UTC, yagom commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    static let shared: UserInformation = UserInformation()
shared 보다 좋은 이름은 없을까요? 제일 좋은 이름이려나요?ㅎㅎ

2020-11-30 12:30 UTC, yagom commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    var userBirthDate: String?
1. 이미 UserInformation 이라는 이름을 갖는데, 프로퍼티의 이름이 user...로 시작할 필요가 있을까요?
2. password는 한단어 아닌가요? :p 
3. 이미지를 String으로 나타낼 예정인가요? 왜 String 타입으로 정의했을까요?
4. 생일도 String 타입으로 나타내는게 적절한 선택일까요?

2020-11-30 14:32 UTC, jryoun1 commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    static let shared: UserInformation = UserInformation()
@yagom 
apple singleton 관련 공식문서에서 shared라고 쓰는 것을 보기도했고, 실제로도 shared를 썼을 때 가장 명시적으로 singleton을 사용했다는 느낌을 주는 것 같아서 shared라는 이름을 사용했습니다.

2020-11-30 14:33 UTC, jryoun1 commented
@yagom 
step1 코드리뷰 사항 수정했습니다!! 확인부탁드려요~

2020-11-30 15:39 UTC, yagom reviewed
몇 가지 고민거리 남겨두었습니다 :) 
원한다면 머지 요청주세요.

2020-11-30 15:39 UTC, yagom commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    var imagePath: String?
path를 표현하는 타입은 String 뿐일까요? Path나 URL이라는 타입은 없나요? 혹시 있다면 String 타입을 유지해야 할 이유가 있을까요?

2020-11-30 15:39 UTC, yagom commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    var birthDate: Date?
String을 사용하는 것과 Date를 사용하는 것에 차이가 있을까요? 있다면 장단점은 무엇이 있을까요?

2020-11-30 15:39 UTC, yagom commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    var imagePath: String?
path를 간직하고 있다면, 다음 Step에서 요구하는 crop한 사진은 어떻게 표현할 수 있을까요?

2020-11-30 15:44 UTC, wonhee009 commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    var imagePath: String?
@yagom 저희가 다음 step의 crop을 생각지 못해서 String으로 했습니다. 생각해보니 crop한 사진을 UIImagepicker에서 UIImage로 가져올 수 있어서 UIImage로 타입을 바꿉니다.

2020-11-30 23:28 UTC, yagom commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    var imagePath: String?
네, 여기서 머지할까요 아님 추가커밋 예정인가요?

2020-12-01 02:06 UTC, wonhee009 commented on SignUpFlow/SignUpFlow/UserInformation.swift
> +    var imagePath: String?
@yagom 머지 요청드립니다!

2020-12-01 05:31 UTC, merged