Step2 : 로그인 화면 구현 (솔, 리나)
yagom-academy/ios-signup-flow pull request #17
Opened 2020-12-02 03:08 UTC by soleJin

-뷰를 스토리보드로 구현
-화면구성요소 배치
-텍스트필드가 채워지지 않은 상태로는 로그인 안됨 알럿 구현
(로그인 화면이 없어서 다 채워져도 로그인 비활성화 알럿이 뜹니다)
-id텍스트필드의 리턴키는 next키로 바꾸고, next키를 누르면 바로 password텍스트필드에 커서가 이동되도록 구현
-password텍스트필드는 secure
-password텍스트필드의 리턴키는 done키로 바꾸고, done키를 누르면 키보드가 사라지도록 구현(resignFirstResponder)
-키보드가 보이는 상태에서 텍스트필드 외의 영역을 터치하면 키보드가 사라지도록 구현(endEditing)
-회원가입 버튼을 터치하면 모달방식으로 화면 이동

고민되는 부분(앱 전환방식)
-화면에서 회원가입버튼을 누를 때 화면전환은 모달,
회원가입을 하는 동안의 화면전환은 내비개이션을 생각하고 있는데 그대로 진행해도 될까요?

2020-12-02 03:32 UTC, yagom reviewed
:) 잘 했습니다.

몇 가지 고민거리 남겨두었어요.
코멘트로 질문도 있어요.

화면에서 회원가입버튼을 누를 때 화면전환은 모달,
회원가입을 하는 동안의 화면전환은 내비개이션을 생각한 이유가 있나요?

2020-12-02 03:32 UTC, yagom commented on SignUpFlow/SignUpFlow/SignUpViewController.swift
> +    @IBAction func dismissPage() {
Page라는 표현은 어떻게해서 사용하게 되었을까요?

2020-12-02 03:32 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
textField의 Return 기능을 수행할것냐 묻는 것 같은데요, 그럼 true를 반환해주면 어떤 일이 발생하나요?
왜 이런 딜리게이트 메서드를 사용하게 됐나요?

2020-12-02 03:32 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    @IBAction func tapView(_ sender: UITapGestureRecognizer) {
제스쳐 인식기를 사용했군요!
UIView의 touchesBegan 메서드를 재정의하지 않고 제스쳐 인식기를 사용한 이유가 있나요?

2020-12-02 03:32 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +            systemAlert()
id field에서는 얼럿을 보여주지 않아도 괜찮을까요? 사용자 입장에선 전부 다 입력하고 나서 얼럿을 보면 허망하지 않을까요?

그나저나 알럿을 꼭 보여줘야 하는 상황일까요?

2020-12-02 03:32 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +            systemAlert()
https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/feedback/

2020-12-02 03:32 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    @IBAction func touchUpSignIn(_ sender: UIButton) {
굳이 로그인 버튼에 액션을 연결할 필요가 있을까요? 왜 이렇게 하기로 결정했나요?

2020-12-02 03:32 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    func systemAlert() {
이 메서드 내부에 적인 문자열들은 앞으로도 다시 쓰이거나 변경될 여지가 없는 문자열들일까요?

2020-12-02 03:52 UTC, lina0322 commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    @IBAction func tapView(_ sender: UITapGestureRecognizer) {
touchesBegan은 `탭을 몇번 했는지, 몇개의 손가락으로 터치`를 했는지를 확인(?)하는 느낌이라면, TabGestrure는 `탭`하는 것을 인식하는 느낌이고 이게 평소에 키보드를 내릴때 사용했던 액션과 더 어울린다고 생각해서 사용했습니다!

2020-12-02 03:53 UTC, lina0322 commented on SignUpFlow/SignUpFlow/SignUpViewController.swift
> +    @IBAction func dismissPage() {
회원가입 페이지로 들어간 것을 닫는 느낌이라서, page를 사용해보았는데 어색할까요?😔
cancelPage
cancelView
dismissView
dismissSignUpView 등등 여러가지를 고민했었는데, naming은 여전히 어려운 것 같습니다😭

2020-12-02 04:28 UTC, lina0322 commented
### [1번]
> 화면에서 회원가입버튼을 누를 때 화면전환은 모달,
회원가입을 하는 동안의 화면전환은 내비개이션을 생각한 이유가 있나요?

이번 프로젝트가 회원가입 페이지이긴 하지만, 실제로 어플을 만들게되면 로그인이 되고 그 화면을 타고타고 들어가는 것이 주된 흐름이라고 생각했습니다. 
그래서 회원가입 페이지 자체가 뜨는 것은 모달이라고 생각했고, 대신 회원가입은 플로우가 있어서 네비게이션으로 해야겠다고 생각했습니다!

### [2번]
> textField의 Return 기능을 수행할것냐 묻는 것 같은데요, 그럼 true를 반환해주면 어떤 일이 발생하나요?
왜 이런 딜리게이트 메서드를 사용하게 됐나요?

사실 명확하게 이해한 것은 아니어서 두서가 없지만....😥 제가 이해한 바로는,
The text field calls this method whenever the `user taps the return button.` 
이 문구를 보고 리턴버튼을 눌렀을때 동작하는 메서드라고 생각했습니다.
또한 예시로 
For example, if you want to dismiss the keyboard when the user taps the return button, your implementation can `call the resignFirstResponder()` method.
딱 제가 원하는 기능을 보여주길래 잘 어울리는 짝궁이라고 생각해서 사용하게 되었습니다!

리턴 값에 대해서는
true if the text field should implement its `default behavior` for the return button; otherwise, false.
`기본 동작`이 무엇인지는 모르겠지만 기본 동작은 해야할것 같아서... true로 했는데 기본동작에 대해서 더 알아보도록 하겠습니다😭

### [3번]
> id field에서는 얼럿을 보여주지 않아도 괜찮을까요? 사용자 입장에선 전부 다 입력하고 나서 얼럿을 보면 허망하지 않을까요?
그나저나 알럿을 꼭 보여줘야 하는 상황일까요?

> 굳이 로그인 버튼에 액션을 연결할 필요가 있을까요? 왜 이렇게 하기로 결정했나요?

로그인 버튼이 정상적으로 구현이 되었다면, 네비게이션을 타고 새로운 뷰로 떠났겠지만.... 지금은 구현을 하기 힘들고 그렇다고 로그인 버튼이 아무 작동도 안하면 너무 심심할 것 같아서 시작된 일이 이렇게 커져버렸습니다ㅎㅎㅎㅎ.....
우선 _Avoid unnecessary alerts._ 을 위해서 아이디와 비밀번호 관련해서는 alert를 제거하였고, 입력이 안된 상황에 대해서 어떤 피드백을 줄 것인지는 조금 더 고민해보도록 하겠습니다.

2020-12-02 04:51 UTC, daheenallwhite commented on SignUpFlow/SignUpFlow/SignUpViewController.swift
> +    @IBAction func dismissPage() {
page 사용하는 경우도 본 적 있는데 page 를 쓴다고 해서 어색하다? 고 보긴 어려울 것 같아요
물론 제 느낌엔 page 는 paging 하는(좌우 스와이핑으로 뷰가 전환 되는) 뉘앙스도 좀 있는 것 같구요

2020-12-02 05:11 UTC, idevjinie commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +            systemAlert()
먼저, 얼럿의 역할에 대한 고민이 필요할 듯해요.
얼럿은 중요한 경고를 표시할 때 사용하는데, 아이디나 패스워드가 비어있는 것이 치명적인 상황일까요?
얼럿이 띄워진다면 사용자가 탭하는 동작이 발생할 텐데, 사용자를 방해하지 않고도 텍스트필드가 비어있다는 것을 인지시킬 수 있는 방법은 없을까요?
또, 야곰의 의견처럼 전부 입력하고도 어떠한 메시지를 거쳐야 할 필요가 있을까요?

얼럿 관련 피드백에 대해 솔과 리나가 의견을 나눠보면 좋겠습니다! 모각코 채널로 캠퍼들을 소환해 다 같이 토의해도 좋을 것 같아요 🥰

2020-12-02 09:16 UTC, lina0322 commented
@yagom @daheenallwhite @idevjinie 

추가로 주신 코멘트 보고, 솔과 함께 다른 어플을 둘러봤는데 로그인이 안되는 경우(아이디, 비밀번호를 입력하지 않거나 틀린 경우도 포함) 대부분 라벨느낌으로 출력을 해주는 것을 확인했습니다! alert를 삭제했고, 라벨로 표현해보았습니다~

..그리고 제가 step3에 2를 merge하려다가 잘못해서 step3 화면 구성한 부분이 딸려왔어요...😅

2020-12-02 11:27 UTC, yagom requested changes
ㅎㅎ 심심해서 만든 것들이 세상을 바꿔놓는 것들이 참 많죠
git이라던지 linux라던지... 하핳

저는 어차피 동작이 없으면 로그인 버튼을 disable 해주면 어떨까 생각해봤어요.
그런데, 기능이 구현되지 않은 구성요소에 대해서 애플의 심사지침은 어떤지도 살펴보면 좋을것 같아요.

메서드 이름 중 대문자로 시작하는 메서드 이름은 바꿀 필요가 있기에 Request changes 남깁니다. 잘 하고 있어요~! 그리고 enterId 처럼 enterID를 사용하지 않는 이유도 궁금합니다.

2020-12-02 11:27 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +        guard textField.text != "" else {
text 프로퍼티의 타입이 무엇인가요?
nil과 ""은 같은 걸까요?

2020-12-02 11:27 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    func IsFullfill(textField: UITextField) -> Bool {
메서드는 소문자로 시작합니다

2020-12-02 11:27 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    func makeLabel(text label: UILabel, to message: Message) {
메서드 이름이 make...인데, 실제로 하는 일은 레이블을 만든다기 보다는 메시지를 레이블에 셋팅하는 역할인 것 같아요.
make.. 하면 뭔가를 만들어서 줄 것 같지 않나요? 알바생이 햄버거를 만들어서 주는것 처럼요

2020-12-02 11:27 UTC, yagom commented on SignUpFlow/SignUpFlow/message.swift
> +}
```swift
struct Message {
    static let existedId = "이미 존재하는 아이디입니다."
    static let enterId = "아이디를 입력해주세요."
///....
}
```
이 코드와는 어떤 점이 다르고 서로 언제 활용하면 좋을지 비교해보는 것도 좋겠어요.
https://blog.yagom.net/538/

2020-12-02 11:27 UTC, yagom commented on SignUpFlow/SignUpFlow/message.swift
> +    case empty = ""
empty를 만들어 두고 `guard textField.text != "" else {` 등의 코드에서 사용하지 않을 이유가 있을까요? :)

2020-12-02 12:05 UTC, lina0322 commented
@yagom 

### [1번]
> 저는 어차피 동작이 없으면 로그인 버튼을 disable 해주면 어떨까 생각해봤어요.

와.. 이건 생각 못했어요! 그것도 방법인 것 같아요.
 
근데 제 생각에는 지금 구조상 다시 enable될 일이 없는 것 같은데, disable하는 건 없는거나 마찬가지라고 생각이들어요.
계속 누르지도 못할 버튼을 만드는건 제가 생각하기엔 조금 이상해요.😅 라벨이랑 다를 바가 없다..? 이런 느낌?!
 
그리고 기능 명세서에 버튼이 존재하기 때문에, 그리고 로그인 페이지인데 버튼이 없는건 더 이상하기 때문에 사용하지 않는 버튼이라고 삭제하는 것도 이상하겠죠...?

그래서 버튼을 두자니...? 버튼을 눌렀는데 오히려 아무 동작이 없다면 이것도 이상한것 아닐까요?!

이런 생각의 흐름의 끝에, 버튼을 눌렀을때 `지금 로그인 기능이 활성화 되어있지 않다`고 하는 alert를 띄우고 싶었던 것 같고 그렇게... 저는 더 먼 곳으로 빠져버렸죠....

결론적으로 지금은, alert는 과한거같고, 아무것도 없는 빈 페이지도 로그인이 안되는 경우도 있어서 무작정 보낼 수는 없고, label을 이용해서 표시할 수 있도록 변경했습니다!

> 그런데, 기능이 구현되지 않은 구성요소에 대해서 애플의 심사지침은 어떤지도 살펴보면 좋을것 같아요.

말씀해주신 심사지침을 보았을때도 `앱에 숨겨져 있거나, 비활성화되어 있거나, 문서화되지 않은 기능이 없어야 합니다. `가 있기 때문에, 저희는 disable보다는 라벨로 표현하는 것을 선택하게 되었습니다...!


### [3번]
> enterId 처럼 enterID를 사용하지 않는 이유도 궁금합니다.



### [3번]
> text 프로퍼티의 타입이 무엇인가요?
nil과 ""은 같은 걸까요?

text의 프로퍼티 타입을 String? 이라고 생각했었고, 확인차 커멘드에 찍어보니 Optional<String>가 나옵니다!!🥳
그리고 사실 저 그거 두 개 다 해봤는데 nil은 작동이 안되고, 왜 안될까 했더니 
그게 nil과 ""의 차이인 것 같아서 ""이걸로 바꾸게 되었습니다. 
nil과 ""의 차이로 제가 정말 좋아하는 사진이 있는데
![image](https://user-images.githubusercontent.com/49546979/100869031-cc028280-34df-11eb-86cf-190fc17fef07.png)
왼쪽이 "", 오른쪽이 nil....
왼쪽은 있긴 있는거에요 뭔가 존재는 하는거죠, 근데 nil은 진짜 아무것도 없는거에요
누군가가 __왼쪽은 희망이 남아있다__ 고 하더군요.
이 사진에게 감사합니다...

 ### [4번]
```swift
enum Message: String {
    case existedId = "이미 존재하는 아이디입니다."
    case enterId = "아이디를 입력해주세요."
    case enterPassword = "패스워드를 입력해주세요."
    case empty = ""
}
```
```swift
struct Message {
    static let existedId = "이미 존재하는 아이디입니다."
    static let enterId = "아이디를 입력해주세요."
///....
}
> 이 코드와는 어떤 점이 다르고 서로 언제 활용하면 좋을지 비교해보는 것도 좋겠어요.

아, 이걸 보면서 enum에 같은 타입만 넣을 수 있는 것을 안타까워했던 과거 제가 떠올랐어요.😱
알려주신 방법을 사용해도, enum과 비슷한 방법으로 사용할 수 있을 것 같다는 생각이 들어요!
가장 큰 차이는 역시 제가 맨 처음 깨달은 저 후회와 관련있다는 생각이 듭니다!

근데 지금은 우선 저 Message를 label에 넣어줄 문자열로 사용하고있고, 
enum에 들어있는 케이스에서만 골라서 넣고싶다보니
사용하는 함수에서도 불러오기가 enum이 좀 더 편하다는 느낌이 ...!!!!


### [5번]
> empty를 만들어 두고 guard textField.text != "" else { 등의 코드에서 사용하지 않을 이유가 있을까요? :)

2020-12-02 15:54 UTC, soleJin commented
>enterId 처럼 enterID를 사용하지 않는 이유도 궁금합니다.

id가 하나의 단어로 생각하고 id로 작성했어요^^;;
야곰의 의견을 듣고 리나와 상의한 결과 ID로 변경하기 위해 코드를 확인해 보니 저희 코드의 많은 곳에서 id를 사용하고 있었습니다.
그대로 ID로 바꾼다면 대문자로 시작하는 프로퍼티명이 되기 때문에 userID처럼 네이밍을 해야할 것 같은데
모두 같은 의미의 ID지만 네이밍을 다 다르게 해야 할까요?
그것만 빼고 바꾸자니 id와 ID가 혼용되서 통일성이 없어보일 것 같아 어떻게하는게 좋을지 조언을 구하고 싶습니다!

2020-12-02 15:55 UTC, lina0322 commented
@yagom 

### [2번]
> text 프로퍼티의 타입이 무엇인가요?
nil과 ""은 같은 걸까요? 

text의 프로퍼티 타입을 String? 이라고 생각했었고, 확인차 커멘드에 찍어보니 Optional String이 나옵니다!!🥳
그리고 사실 저 그거 두 개 다 해봤는데 nil은 작동이 안되고, 왜 안될까 했더니 
그게 nil과 ""의 차이인 것 같아서 ""이걸로 바꾸게 되었습니다. 
nil과 ""의 차이로 제가 정말 좋아하는 사진이 있는데
![image](https://user-images.githubusercontent.com/49546979/100869031-cc028280-34df-11eb-86cf-190fc17fef07.png)
왼쪽이 "", 오른쪽이 nil....
왼쪽은 있긴 있는거에요 뭔가 존재는 하는거죠, 근데 nil은 진짜 아무것도 없는거에요
textField에서도 ""은 내용물이 비어있는 느낌이고, nil은 존재자체를 안하는 느낌이어서
""가 맞는 표현이라고 생각했고, 실제로도 그렇게 해야만 올바르게 동작이 되었습니다!
아 그리고 누군가가 __왼쪽은 희망이 남아있다__ 고 표현하더라고요...ㅎㅎ..ㅎㅋ..

 ### [3번]
```swift
enum Message: String {
    case existedId = "이미 존재하는 아이디입니다."
    case enterId = "아이디를 입력해주세요."
    case enterPassword = "패스워드를 입력해주세요."
    case empty = ""
}
```
```swift
struct Message {
    static let existedId = "이미 존재하는 아이디입니다."
    static let enterId = "아이디를 입력해주세요."
///....
}
```
> 이 코드와는 어떤 점이 다르고 서로 언제 활용하면 좋을지 비교해보는 것도 좋겠어요.

아, 이걸 보면서 enum에 같은 타입만 넣을 수 있는 것을 안타까워했던 과거 제가 떠올랐어요.😱
가장 큰 차이는 역시 이 후회와 관련있다는 생각이 듭니다!

물론 struct에도 같은 타입들을 담을 수 있으니
알려주신 방법을 사용해도, enum과 비슷한 방법으로 사용할 수 있을 것 같다는 생각이 들어요!

그런데 지금은 우선 저 Message를 label에 넣어줄 문자열로 사용하고있고, 
enum에 들어있는 케이스에서만 골라서 넣고싶다보니
사용하는 함수에서도 불러오기가 enum이 좀 더 편하다는 느낌이 ...!!!!


### [4번]
> empty를 만들어 두고 guard textField.text != "" else { 등의 코드에서 사용하지 않을 이유가 있을까요? :)

오늘 리뷰가 제가 고민했던 것들이 많이 나오니 신기하네요!!!
처음에 ""로 했다가, empty가 생성되고 난 후에 empty로 변경해보았는데
문구가 뭔가 Message.empty라는게 
지금 전체적으로 메세지 enum을 라벨에 띄우는 용도로 사용하고있는데, 
그 enum과 비교하는게 좀 이상하다는 느낌을 받았습니다.
그리고 만약 나중에 empty를 다른 문구로 혹시라도 바꾼다면
여기는 주로 사용하는 곳이 아닌 코드인데, 영향을 미칠 것 같아서(의존성을 높일 것 같아서..?!)
오히려 ""가 명확하다고 생각했습니다!

2020-12-03 02:46 UTC, yagom reviewed
@lina0322 Optional("") 대신에 정말로 nil이 나오는 경우도 있지 않을까요? 말 그대로 정말로 옵셔널이니까요. 그렇다면 그럴 때는 저 코드가 정상적으로 역할을 해낼 수 있을까요?

@soleJin ID는 identification의 줄임말이죠.
https://swift.org/documentation/api-design-guidelines/ 문서의 **Follow case conventions** 부분을 찾아보면 힌트가 있을 것 같아요.

코멘트와 질문 남겨뒀어요.
추가 커밋하고 싶다면 추가 커밋을, 머지 요청하고 싶으면 머지요청 해주세요 :)

2020-12-03 02:46 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +    func isFullfill(textField: UITextField) -> Bool {
혹시 메서드 이름을 바꿀 때 하나씩 찾아서 바꾸었나요?
이름 바꿀 땐 Xcode의 Refactor - Rename 기능을 꼭 사용하길 추천합니다!

2020-12-03 02:46 UTC, yagom commented on SignUpFlow/SignUpFlow/MainViewController.swift
> +        changeLabel(text: statusMessageLabel, to: .empty)
레이블 자체를 변경하는 걸까요?
레이블의 텍스트 자체를 변경하는 이름이라면
`changeLabelText(with text: String, at label: UILabel)`
은 어때요? 조금 더 고민해봐도 좋고요 :)

2020-12-03 02:56 UTC, lina0322 commented
@yagom  
> Optional("") 대신에 정말로 nil이 나오는 경우도 있지 않을까요? 말 그대로 정말로 옵셔널이니까요. 그렇다면 그럴 때는 저 코드가 정상적으로 역할을 해낼 수 있을까요?

이거 야곰한테 댓글쓸때만해도 뭔가 명확하게 이거다! 라고 생각했는데,
자꾸 생각해보고 문서를 보고 하니까 점점 더 미궁에 빠지고있어요.... 좀 더 생각해볼게요!

머지요청드립니다
감사합니다🙇🏻‍♀️

2020-12-03 03:08 UTC, merged